apiVersion: projects.gitlab.m.crossplane.io/v1alpha1
kind: Project
metadata:
  name: crossplane-test-project
spec:
  forProvider:
    name: "crossplane test"
    namespaceId: 101312059
    description: "crossplane test project"
    buildGitStrategy: "fetch"
  providerConfigRef:
    name: gitlab-provider
    kind: ProviderConfig
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-project-crossplane-test-project
